server:
  port: 9100
spring:
  profiles:
    active: dev
  redis:
    host: 127.0.0.1
    port: 6379
rocketmq:
  name-server: 127.0.0.1:9876
  producer:
    group: approval-group
    send-message-timeout: 3000
    retry-times-when-send-async-failed: 3
    retry-times-when-send-failed: 3